# Generated by Django 2.0.3 on 2018-03-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_logo', models.CharField(max_length=1000)),
                ('crypto_name', models.CharField(max_length=500)),
                ('crypto_market_cap', models.CharField(max_length=500)),
                ('crypto_price', models.CharField(max_length=500)),
                ('crypto_volume', models.CharField(max_length=500)),
                ('crypto_supply', models.CharField(max_length=500)),
                ('crypto_change', models.CharField(max_length=500)),
                ('crypto_graph', models.CharField(max_length=1000)),
            ],
        ),
    ]
