# Generated by Django 2.0.3 on 2018-03-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodisplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptos',
            name='crypto_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
