# Generated by Django 2.0.3 on 2018-03-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodisplay', '0003_cryptos_value_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptos_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_crypto_number', models.CharField(max_length=500)),
                ('details_crypto_name', models.CharField(max_length=500)),
                ('details_crypto_source', models.CharField(max_length=500)),
                ('details_crypto_pair', models.CharField(max_length=500)),
                ('details_crypto_volume', models.CharField(max_length=500)),
                ('details_crypto_price', models.CharField(max_length=500)),
                ('details_crypto_volume_percent', models.CharField(max_length=500)),
            ],
        ),
    ]
